server:
  port: 8080
  servlet:
    # ???????
    context-path: /draw-api

spring:
  application:
    name: voice-draw-api
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

# ????????
logging:
  # ??????
  config: classpath:log/logback-spring.xml

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.xym.voicedrawingapi.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456